### ISSUE TITLE
Api discuss

### ISSUE THREAD

**Issue by djx314** [zio/zio-logging#143]
https://github.com/zio/zio-logging/blob/64c7ed9dd5e49275c369cae92f8fc125f571d0d2/core/src/main/scala/zio/logging/log.scala#L25-L31

Here R is already <: Logging, is it need to declare return type to `ZIO[Logging with R, E, A1]` ? or `ZIO[R, E, A1]` is OK ?
Now I'm using nat programming to rebuild a new zio api and rebuild the api only `log.scala` in zio-logging. I find that just use `XIO[R, E, A1]` is no problem in my code. Just create this issue.

Here's my code

https://github.com/djx314/xio/blob/052c663846a7380610e1027625a6b2975d4c62b4/a05-XIO/xio-logging/src/main/scala/xio/logging/Log.scala#L57-L62

**Comment by pshemass** [comment]
Hi @djx314, it needs  both because one is requirement for `Logging` since this is object method we need to express that someone will provide instance of `Logging` to run our program. `R` is coming from the function that you can pass. Imagine that this will be your custom annotation that will beginning of your operation.
```scala
val OperationTime = LogAnnotation[Option[Datetime]]("my-operation", None, (_, v) => v, _.toString)
```   
then to grab time in ZIO you will probably use `zio.clock`
```
import zio.clock._
val result: ZIO[Logging with Clock, Nothing, Unit] = 
  log.locallyM(ctx => currentDateTime.orDie.flatMap(time => ctx.annotate(OperationTime, Some(time))){ ZIO.unit }
```

let me know if that is clear

**Comment by djx314** [comment]
Let me have a test when have some time, just keep it open. Thanks.

**Comment by pshemass** [comment]
@djx314 there is test for this in codebase that may help https://github.com/zio/zio-logging/blob/master/core/src/test/scala/zio/logging/LoggerSpec.scala#L95
